# Sử dụng một base image chứa Node.js
FROM node:14

# Thiết lập thư mục làm việc trong container
WORKDIR /app

# Sao chép mã nguồn của ứng dụng vào container
COPY . .

# Cài đặt dependencies của ứng dụng
RUN npm install

# Mở port mà ứng dụng sẽ lắng nghe
EXPOSE 3000

# Khởi động ứng dụng khi container được chạy
CMD ["npm", "start"]
